### ISSUE TITLE
OpenFOAM-Grasshopper coupling issues

### ISSUE THREAD

**Issue by albmorsam** [kastnerp/HeatFlux#1]
Hi,

first of all great article and very interesting! however I am quite new in this platfform and using OpenFOAM so i am trying to learn as much as I can.

I want to reply the same than is done in the article but I have a few question in the **pre-processing & simultation** part for now:

1- how can I assign the values defined in the folders 0 and constant what correspond to boundary conditions and thermal properties to each region (from 0 to 13) in rhino- grasshopper environment?

2- How can I call a .bat file in C# component in grasshopper? 

another alternative I have tried is to copy/paste the code for example for "blockmesh"

" setlocal
call "C:\Program Files\blueCFD-Core-2017\\setvars.bat"
set PATH=%HOME%\msys64\usr\bin;%PATH%       (line 59)
cd /d %~dp0
blockMesh

PAUSE  "

in C# component in grasshopper but i get two errors. the error about "\" in line 59 can be solved removing the caracter that is located after usr but I don't know if it is right to do it. The other error in line 59 I don't know how to do it. I have read that this line would only work fine for BlueCFD environment and not for windows cmd environment but I am sure I am wrong.

3- Is snappyHexMesh/cfMesh running automatically with OpenFOAM to generate 3d resut visuralization (heat flux)?

4- To run the pre-processing part and simulation then what I have to do this in order:

- first,  define the thermal bridge geometry in rhino
- second, assign boundaries conditions and thermal properties to each region
- third, run script in C# for each .bat file

 run_blockMesh.bat
 run_cellSet.bat
 run_splitMesh.bat
 run_changeDicts.bat
 run_chtMultiRegionFoam.bat

then, at the end, should I see the heat flux-temperature visualization (Figure 4 from the article) or something similar in 3D (I am confused with waht is said in the ast part of the article-conclusions)? do I miss something else in the process?

Regards and thanks in advance

**Comment by kastnerp** [comment]
Hi @albmorsam,

Without going into the details, could you please see if my last [commit ](https://github.com/kastnerp/HeatFlux/commit/f21e4a58e2fd7d3f5d8c2660f42f47a25b2db029 )works for you? 
You were correct that it didn't work due to some OpenFOAM version inconsistencies. Currently, everything needs to be run via Docker and OF 4.1. I unfortunately don't have time to update the setup for BlueCFD.

Best,

Patrick

**Comment by kastnerp** [comment]
> 1- how can I assign the values defined in the folders 0 and constant what correspond to boundary conditions and thermal properties to each region (from 0 to 13) in rhino- grasshopper environment?
>

Set them here 
![image](https://github.com/kastnerp/HeatFlux/assets/1919773/ba12065e-fba8-44a9-bd95-9484c5e146da)


> 2- How can I call a .bat file in C# component in grasshopper?
> 
You don't have to, just call from the Windows Explorer directly.
> 
> 3- Is snappyHexMesh/cfMesh running automatically with OpenFOAM to generate 3d resut visuralization (heat flux)?
> 
 
snappyHexMesh is not needed for this case.


> 4- To run the pre-processing part and simulation then what I have to do this in order:

Run everything in order that you see in `run_all.bat`.

Best,

Patrick

**Comment by albmorsam** [comment]
Thanks for your feedback.

For the point 1, what is the next grasshopper component that you use after the panel grasshopper component from your image.

For the point 2,  I am a bit confused because I have to run this in  Docker and OF 4.1.  but I have to call .bat files in window explorer.

What do you mean window explorer ? in CDM?

Do you have a very small example of 2-3 region thermal bridge so visually it will help me?

Apologize and regards

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by albmorsam** [comment]
Let me go further to see how I can do it and I will go back to you.
I am pretty new in this and I need more time that normally.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kastnerp** [comment]
> For the point 1, what is the next grasshopper component that you use after the panel grasshopper component from your image. 

You can see the downstream components once you open the GH file and navigate to the upper left.

> For the point 2, I am a bit confused because I have to run this in Docker and OF 4.1. but I have to call .bat files in window explorer. 

The .bat files give you a shortcut to easily run the commands. You could just as easily copy the commands and run them in the terminal.

> Do you have a very small example of 2-3 region thermal bridge so visually it will help me? 

I unfortunately do not. OpenFOAM is difficult, there are no shortcuts. If you really would like to understand what is going on, you'd have to reverse engineer a complex case, and put it back together. 

Best,

Patrick

**Comment by albmorsam** [comment]
Thanks a lot. I really appreciate your help and all updating you did in the github. I saw the script .ghx and I will do now my best from this step. I thinkany people will appreciate these new updates. Sorry if I bother your in some point. Have a good week!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by albmorsam** [comment]
Hi, last question

Where can I download OpenFOAM 4.1 for window?

https://openfoam.org/version/4-1/


Is it enough with docker in the link below?


https://www.openfoam.com/download/openfoam-installation-on-windows-docker



Regards



Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kastnerp** [comment]
You would just install Docker on Windows, it will pull OF 4.1 automatically.

**Comment by albmorsam** [comment]
thanks once again.

Do you mean the image below?

[cid:aa5509cf-8295-4ef4-a12f-db214bf66996]

then when I click play in the omponent C# from your grasshopper file (you uploaded yesterday), it will run the script automatically?


________________________________
De: Patrick Kastner ***@***.***>
Enviado: miércoles, 7 de junio de 2023 15:31
Para: kastnerp/HeatFlux ***@***.***>
Cc: albmorsam ***@***.***>; Mention ***@***.***>
Asunto: Re: [kastnerp/HeatFlux] OpenFOAM-Grasshopper coupling issues (Issue #1)


You would just install Docker on Windows, it will pull OF 4.1 automatically.

**Comment by albmorsam** [comment]
Hi,

Sorry again. I know that I am very annoying. I am close to get it . i have done all in grasshopper

first of all, I guess that this panel should not adapt to my case and leave it as it is

[cid:5aeee35a-62b6-44f4-a4e9-275be87911b3]


secondly,

[cid:aa824336-9c41-4234-ac08-b4b2f0f94bb9]

 I generate the .bat files in my desktop and I double click in the run_all.bat file (which includes OpenFOAM’s chtMultiregionFoam solver that  is capable of predicting temperature distributions)

[cid:fd439165-9919-480d-bc9f-b3a692d2df24]

Running perfectly but when it fininshes in cdm I cannot visualize the temperature distribution and isotherms (Figure 6 from your article).


  1.  how can I get those images?
  2.  how did you manually calculate the heat flux manually using Fourier's law of heat conduction to every zone in the simulation domain as you explained in your article?
  3.  is there a way to calculate the lineal thermal bridge (2d)? Typical value enteres in energy simulations

Regards

________________________________
De: Patrick Kastner ***@***.***>
Enviado: miércoles, 7 de junio de 2023 15:31
Para: kastnerp/HeatFlux ***@***.***>
Cc: albmorsam ***@***.***>; Mention ***@***.***>
Asunto: Re: [kastnerp/HeatFlux] OpenFOAM-Grasshopper coupling issues (Issue #1)


You would just install Docker on Windows, it will pull OF 4.1 automatically.

**Comment by albmorsam** [comment]
i forgot to oinclude this image from docker that is generated after the simulation

[cid:9e7fd49e-fcb5-4a29-bba4-f2e401413232]
________________________________
De: Patrick Kastner ***@***.***>
Enviado: miércoles, 7 de junio de 2023 15:31
Para: kastnerp/HeatFlux ***@***.***>
Cc: albmorsam ***@***.***>; Mention ***@***.***>
Asunto: Re: [kastnerp/HeatFlux] OpenFOAM-Grasshopper coupling issues (Issue #1)


You would just install Docker on Windows, it will pull OF 4.1 automatically.

**Comment by kastnerp** [comment]
You'd need to post your screenshots directly on Github, I cannot see them if you answer via email.

**Comment by albmorsam** [comment]
Apologise my bad. All done in the tab issue in github

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Patrick ***@***.***>
Enviado: jueves, 8 de junio de 2023 17:21
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [kastnerp/HeatFlux] OpenFOAM-Grasshopper coupling issues (Issue #1)


You'd need to post your screenshots directly on Github, I cannot see them if you answer via email.
