### ISSUE TITLE
results and visualization

### ISSUE THREAD

**Issue by albmorsam** [kastnerp/HeatFlux#2]
Hi,

Sorry again. I am close to get it . i have done all in grasshopper (image 2) 
![image 2](https://github.com/kastnerp/HeatFlux/assets/125660123/8bc49090-282e-442a-bd82-91e0ee2d6443)

first of all, I guess that this panel (image 1) should not adapt to my case and leave it as it is
![image 1](https://github.com/kastnerp/HeatFlux/assets/125660123/ff2216d2-01ad-4ad5-abce-945ce8ecdbb3)

secondly, 

 I generate the .bat files in my desktop and I double click in the run_all.bat file (image 3) (which includes OpenFOAM’s chtMultiregionFoam solver that  is capable of predicting temperature distributions)
![image 3](https://github.com/kastnerp/HeatFlux/assets/125660123/fceaafc8-2452-4a32-af6f-c585329ee3f1)

Running perfectly but when it fininshes in cdm I cannot visualize the temperature distribution and isotherms (Figure 6 from your article).

1- how can I get those images? image 6. 
![image 6](https://github.com/kastnerp/HeatFlux/assets/125660123/1f62afd8-b27d-4dfc-ba7e-e35e2b8b3e57)

2- how did you manually calculate the heat flux manually using Fourier's law of heat conduction to every zone in the simulation domain as you explained in your article?
3- is there a way to calculate the lineal thermal bridge (2d)? Typical value enteres in energy simulations

4- after run_all. bar being running, i generate a container which a few elements. which info can I extract from there (image 4)?
![image 4](https://github.com/kastnerp/HeatFlux/assets/125660123/8cd840ea-4fd7-4328-ba65-ab0fab46aa4b)

Regards

**Comment by kastnerp** [comment]
> 1- how can I get those images? image 6.

Open `case.foam` with Paraview.

> 2- how did you manually calculate the heat flux manually using Fourier's law of heat conduction to every zone in the simulation domain as you explained in your article?

Check `run_heatflux.bat`.

> 3- is there a way to calculate the lineal thermal bridge (2d)? Typical value enteres in energy simulations

This should be possible, but would have to be done manually. I don't think we've done it in the paper, so I cannot assist with it, unfortunately. 

> 4- after run_all. bar being running, i generate a container which a few elements. which info can I extract from there (image 4)?
These are just exited (old) containers, just ignore.

Best,

Patrick

**Comment by albmorsam** [comment]
Thanks a lot. you don't know how much I appreciate your support.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by albmorsam** [comment]
Hi,

1- I have been running my model but i do not generate any case.foam as I can see in your case in github. How can I generate this file?

2- I run heatflux.bat (double click) but the simulation stops. is it due the unexpected token (please see image attached)
![image 1](https://github.com/kastnerp/HeatFlux/assets/125660123/4ab2340a-d819-4849-a999-a43e60cf671d)
