### ISSUE TITLE
Result and visualization continuation

### ISSUE THREAD

**Issue by albmorsam** [kastnerp/HeatFlux#3]
hi,

1- I have been trying to simulate the case but I do not get any "case.foam" file to visualize in paraview? How can I generate the file?

I have tried to visualize your "openfoam" in paraview and i get the next message. how can I solve it? would the mesh have been generated with blockmesh component?
![image 2](https://github.com/kastnerp/HeatFlux/assets/125660123/dc04c8ca-180d-43f1-9e39-f103c1fe9ddf)
![image 3](https://github.com/kastnerp/HeatFlux/assets/125660123/030de167-854b-4f4a-b072-5fb0da034872)
![image 4](https://github.com/kastnerp/HeatFlux/assets/125660123/6ad13bce-0c5d-46cd-898a-ac112d1b65f8)

2- I also run the file "run_heatflux.bat" as you said to me but it stops due to unexpected token. do you know the reason why i get it?

![image 1](https://github.com/kastnerp/HeatFlux/assets/125660123/c10d93fc-5f59-40d0-99dd-c30962298084)

3- what info can i get from "run_plot.bat"?

Regards

**Comment by kastnerp** [comment]
> 1- I have been trying to simulate the case but I do not get any "case.foam" file to visualize in paraview? How can I generate the file?

The `case.foam` file is in the parent folder.

> I have tried to visualize your "openfoam" in paraview and i get the next message. how can I solve it? would the mesh have been generated with blockmesh component?

Your case didn't run yet. You need to run the case. Ideally in a folder and not directly on your desktop.

> 2- I also run the file "run_heatflux.bat" as you said to me but it stops due to unexpected token. do you know the reason why i get it?

I fixed this [here](https://github.com/kastnerp/HeatFlux/commit/f89d524cd713f7e9de025ff7af67a6fb217f00a8). Context: OF 4.1 used to have a bug that can't prostprocess ob mesh regions, so I used BlueCFD 5-x for that purpose now. 

Best,

Patrick

**Comment by albmorsam** [comment]
hi,

thanks once again. I run your last case "heat flux" that you did it yesterday. i saved it in a folder in my desktop

![2023-06-10 (2)](https://github.com/kastnerp/HeatFlux/assets/125660123/2166e44b-bd46-406f-9ccb-0317ac8e8abf) 

1- what do you mean with "parent folder"? where can i find it?  i check "system" folder (see image attached) and in the folder docker in my C\\ but I am missing something because I cannot find it.

2- what do you mean running my case? do you mena run the file "run_all.bat" inside the folder? I do it but I get the same error than for the file "run_heatflux.bat"than before i think about polymesh and points file (see both images attached).

![2023-06-10 (3)](https://github.com/kastnerp/HeatFlux/assets/125660123/eeb4aeca-0a41-45b4-84a1-cfeddbac11c8)

![2023-06-10 (1)](https://github.com/kastnerp/HeatFlux/assets/125660123/b6045cc4-464d-4237-b250-4b7c892c33e4)

Regards

**Comment by kastnerp** [comment]
Hi @albmorsam ,

I'd suggest starting with some more basic OF tutorials/cases before you play with this one. This is a fairly complex multiregion case and I now recognize it might not be suitable for beginners. 

Best,

Patrick

**Comment by albmorsam** [comment]
Ok thanks I will. I think it is a good idea to start from the beginning but it is possible to respond my previous questions please to see where I can find the parent folder,..and I will try later to creat block meshes.

Tha ks

**Comment by kastnerp** [comment]
If you check the root folder of the repo you should see a file called `case.foam`.

**Comment by albmorsam** [comment]
What I did it is to create an empty file in editor and save it as an open.foam and I could see the mesh. See the discussion. The new one created ( open issue)

What do you mean root folder of the repo? I am confused . Sorry

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by albmorsam** [comment]
Hi,

sorry I ask this again but, Where is locaated my root folder of the repository? I do not understand this. I try to find out the file in C\\ in particulat in the folder docker or C:\Program Files\blueCFD-Core-2017\OpenFOAM-5.x but I cannot see anything. whether you can lead me to folder approx, I would appreciate it.

Regards
