### ISSUE TITLE
final run

### ISSUE THREAD

**Issue by albmorsam** [kastnerp/HeatFlux#4]
Hi,

I have an updating. I open "run_blockmesh.bat" and I added " at the end of the file. I dont know but it works, maybe it was luck

when i run the file "run_heatflux.bat" i get the image below at the end. where is it supposed to see the final result (heat flux (W/m2) of the simulation to calculate the lineal thermal bridge?

![1](https://github.com/kastnerp/HeatFlux/assets/125660123/8da73cfa-ce7e-4f88-8630-16c6682a0f26)

finally i could run the file "run_all.bat" and generaing the meshes. please see the images if they make sense

![1](https://github.com/kastnerp/HeatFlux/assets/125660123/9e96699d-fbad-41cf-97d3-1ec6dbbd0f61)
![3](https://github.com/kastnerp/HeatFlux/assets/125660123/68712597-1305-44ad-9751-d0b72dcddd0d)
![4](https://github.com/kastnerp/HeatFlux/assets/125660123/b403f83f-6c55-4708-be69-3715b1bf3400)
![8](https://github.com/kastnerp/HeatFlux/assets/125660123/097f3b91-8893-49fb-a3cc-ea2e6cf6eb00)

Regards

**Comment by kastnerp** [comment]
You should see a new field in Paraview called ˋgrad(T)ˋ. Check where it says ˋvtkBlockColorsˋ.

**Comment by albmorsam** [comment]
thanks once again. this was my guess to find a option there for heat flux and temperature but I do not see any of them, do you know why?. however I see the next. see below (grad (T) so in theory it is generated both and working well if I am not wrong
![2023-06-11 (1)](https://github.com/kastnerp/HeatFlux/assets/125660123/9b4083ef-c908-491c-99e3-ea24d58a0921)
![2023-06-11 (3)](https://github.com/kastnerp/HeatFlux/assets/125660123/4b630c3d-14a7-4f42-8976-85c270494be7)

**Comment by kastnerp** [comment]
You are looking at timestep 0 which likely has no heatflux calculated. The questions you are asking are very basic questions and I would suggest again to get started with a basic case, not this one. I will close this issue.

Best,

Patrick

**Comment by albmorsam** [comment]
What I asking previously is an absolute value of heat flux . On the other , I need further investigation about how to use paraview to see heat flux and temperature distribution in the regions. I only responded to your comment in my previous message.sorry for the misunderstanding

**Comment by albmorsam** [comment]
but time 0 is where the boundary/initial conditions live

![2023-06-11 (42)](https://github.com/kastnerp/HeatFlux/assets/125660123/7fc6e84e-67a8-4246-b890-981e81b02179)

when I run "run_chtMultiRegionFoam.bat" individually it looks it is creating a mesh for t=0 and getting this message then the cmd window closes suddenly
![2023-06-11 (23)](https://github.com/kastnerp/HeatFlux/assets/125660123/fcca2f7b-b44e-473e-b40a-7581297b4568)
![2023-06-11 (30)](https://github.com/kastnerp/HeatFlux/assets/125660123/a1f509cd-cc89-4ca1-9d88-8d7a9a5f2a3f)

it looks a a mismatch between the patch type & the boundary condition you've specified, but how to change it?
